name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'nginx-app/values.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set SHA
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Image
        run: |
          docker build -t ghcr.io/sakethg701/devops-capstone:${SHA_SHORT} ./app

      - name: Push Image
        run: |
          docker push ghcr.io/sakethg701/devops-capstone:${SHA_SHORT}

      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag: .*/tag: ${SHA_SHORT}/" nginx-app/values.yaml

      - name: Disable git credential helper
        run: |
          git config --global --unset credential.helper || true

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add nginx-app/values.yaml
          git commit -m "Update image tag to ${SHA_SHORT} [skip ci]" || echo "No changes to commit"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/sakethg701/DevOps-project.git
          git push origin main